ServerEvents.recipes((event) => {
    event.recipes.kubejs.quantum_miner()
        .id("kubejs:quantum_miner/nether/silk_touch")
        .duration(40)
        .perTick(miner => miner
            .inputFE(16384)
        )
        .chance(0.71, miner => miner.outputItems("3x minecraft:glowstone"))
        .chance(0.75, miner => miner.outputItems("minecraft:nether_quartz_ore"))
        .chance(0.57, miner => miner.outputItems("mysticalagradditions:nether_inferium_ore"))
        .chance(0.45, miner => miner.outputItems("minecraft:nether_gold_ore"))
        .chance(0.41, miner => miner.outputItems("minecraft:ancient_debris"))
        .blocksInStructure(2, 2, "kubejs:nether_quantum_modifier", "kubejs:silk_touch_quantum_modifier")

    event.recipes.kubejs.quantum_miner()
        .id("kubejs:quantum_miner/nether/normal")
        .duration(40)
        .perTick(miner => miner
            .inputFE(16384)
        )
        .chance(0.91, miner => miner.outputItems("7x minecraft:glowstone_dust"))
        .chance(0.90, miner => miner.outputItems("2x minecraft:gold_nugget"))
        .chance(0.85, miner => miner.outputItems("2x mysticalagriculture:inferium_essence"))
        .chance(0.75, miner => miner.outputItems("minecraft:quartz"))
        .chance(0.41, miner => miner.outputItems("minecraft:ancient_debris"))
        .blocksInStructure(3, 3, "kubejs:nether_quantum_modifier", "kubejs:auto_smelt_quantum_modifier", "kubejs:blank_quantum_modifier")
        .priority(0)

    event.recipes.kubejs.quantum_miner()
        .id("kubejs:quantum_miner/nether/normal/fortune")
        .duration(40)
        .perTick(miner => miner
            .inputFE(32768)
        )
        .chance(0.93, miner => miner.outputItems("8x minecraft:glowstone_dust"))
        .chance(0.80, miner => miner.outputItems("5x minecraft:gold_nugget"))
        .chance(0.94, miner => miner.outputItems("4x mysticalagriculture:inferium_essence"))
        .chance(0.83, miner => miner.outputItems("2x minecraft:quartz"))
        .chance(0.41, miner => miner.outputItems("minecraft:ancient_debris"))
        .blocksInStructure(3, 3, "kubejs:nether_quantum_modifier", "kubejs:auto_smelt_quantum_modifier", "kubejs:blank_quantum_modifier", "kubejs:fortune_quantum_modifier")
        .priority(1)

    event.recipes.kubejs.quantum_miner()
        .id("kubejs:quantum_miner/overworld/silk_touch")
        .duration(40)
        .perTick(miner => miner
            .inputFE(16384)
        )
        .chance(0.92, miner => miner.outputItems("4x minecraft:deepslate_iron_ore"))
        .chance(0.77, miner => miner.outputItems("2x minecraft:deepslate_coal_ore"))
        .chance(0.75, miner => miner.outputItems("2x mekanism:deepslate_osmium_ore"))
        .chance(0.71, miner => miner.outputItems("2x minecraft:deepslate_copper_ore"))
        .chance(0.70, miner => miner.outputItems("2x thermal:deepslate_silver_ore"))
        .chance(0.68, miner => miner.outputItems("2x thermal:deepslate_nickel_ore"))
        .chance(0.64, miner => miner.outputItems("2x minecraft:deepslate_redstone_ore"))
        .chance(0.62, miner => miner.outputItems("2x minecraft:deepslate_gold_ore"))
        .chance(0.54, miner => miner.outputItems("2x thermal:deepslate_tin_ore"))
        .chance(0.95, miner => miner.outputItems("thermal:deepslate_lead_ore"))
        .chance(0.57, miner => miner.outputItems("mysticalagriculture:deepslate_inferium_ore"))
        .chance(0.52, miner => miner.outputItems("thermal:oil_sand"))
        .chance(0.37, miner => miner.outputItems("evilcraft:dark_ore_deepslate"))
        .chance(0.34, miner => miner.outputItems("thermal:deepslate_sulfur_ore"))
        .chance(0.32, miner => miner.outputItems("thermal:deepslate_niter_ore"))
        .chance(0.31, miner => miner.outputItems("minecraft:deepslate_lapis_ore"))
        .chance(0.29, miner => miner.outputItems("mekanism:deepslate_fluorite_ore"))
        .chance(0.27, miner => miner.outputItems("forbidden_arcanus:deepslate_arcane_crystal_ore"))
        .chance(0.24, miner => miner.outputItems("minecraft:deepslate_diamond_ore"))
        .chance(0.22, miner => miner.outputItems("mekanism:deepslate_uranium_ore"))
        .chance(0.22, miner => miner.outputItems("thermal:deepslate_apatite_ore"))
        .chance(0.21, miner => miner.outputItems("thermal:deepslate_cinnabar_ore"))
        .chance(0.20, miner => miner.outputItems("kubejs:deepslate_certus_quartz_ore"))
        .chance(0.19, miner => miner.outputItems("kubejs:deepslate_quartz_ore"))
        .chance(0.13, miner => miner.outputItems("minecraft:deepslate_emerald_ore"))
        .chance(0.09, miner => miner.outputItems("forbidden_arcanus:runic_deepslate"))
        .blocksInStructure(2, 2, "kubejs:overworld_quantum_modifier", "kubejs:silk_touch_quantum_modifier")

    event.recipes.kubejs.quantum_miner()
        .id("kubejs:quantum_miner/overworld/normal")
        .duration(40)
        .perTick(miner => miner
            .inputFE(16384)
        )
        .chance(0.96, miner => miner.outputItems("6x minecraft:redstone"))
        .chance(0.92, miner => miner.outputItems("4x minecraft:raw_iron"))
        .chance(0.85, miner => miner.outputItems("2x mysticalagriculture:inferium_essence"))
        .chance(0.77, miner => miner.outputItems("2x minecraft:coal"))
        .chance(0.75, miner => miner.outputItems("2x mekanism:raw_osmium"))
        .chance(0.71, miner => miner.outputItems("2x minecraft:raw_copper"))
        .chance(0.70, miner => miner.outputItems("2x minecraft:lapis_lazuli"))
        .chance(0.70, miner => miner.outputItems("2x thermal:raw_silver"))
        .chance(0.68, miner => miner.outputItems("2x thermal:raw_nickel"))
        .chance(0.62, miner => miner.outputItems("2x minecraft:raw_gold"))
        .chance(0.54, miner => miner.outputItems("2x thermal:raw_tin"))
        .chance(0.95, miner => miner.outputItems("thermal:raw_lead"))
        .chance(0.92, miner => miner.outputItems("evilcraft:dark_gem"))
        .chance(0.87, miner => miner.outputItems("mekanism:fluorite_gem"))
        .chance(0.85, miner => miner.outputItems("thermal:sulfur"))
        .chance(0.80, miner => miner.outputItems("thermal:niter"))
        .chance(0.77, miner => miner.outputItems("thermal:apatite"))
        .chance(0.52, miner => miner.outputItems("thermal:oil_sand"))
        .chance(0.40, miner => miner.outputItems("ae2:certus_quartz_crystal"))
        .chance(0.31, miner => miner.outputItems("thermal:cinnabar"))
        .chance(0.30, miner => miner.outputItems("ae2:certus_quartz_dust"))
        .chance(0.27, miner => miner.outputItems("forbidden_arcanus:arcane_crystal"))
        .chance(0.24, miner => miner.outputItems("minecraft:diamond"))
        .chance(0.22, miner => miner.outputItems("mekanism:raw_uranium"))
        .chance(0.19, miner => miner.outputItems("minecraft:quartz"))
        .chance(0.13, miner => miner.outputItems("minecraft:emerald"))
        .chance(0.09, miner => miner.outputItems("forbidden_arcanus:rune"))
        .blocksInStructure(3, 3, "kubejs:overworld_quantum_modifier", "kubejs:blank_quantum_modifier")
        .priority(0)

    event.recipes.kubejs.quantum_miner()
        .id("kubejs:quantum_miner/overworld/auto_smelt")
        .duration(40)
        .perTick(miner => miner
            .inputFE(16384)
        )
        .chance(0.96, miner => miner.outputItems("6x minecraft:redstone"))
        .chance(0.92, miner => miner.outputItems("4x minecraft:iron_ingot"))
        .chance(0.85, miner => miner.outputItems("2x mysticalagriculture:inferium_essence"))
        .chance(0.77, miner => miner.outputItems("2x minecraft:coal"))
        .chance(0.75, miner => miner.outputItems("2x mekanism:ingot_osmium"))
        .chance(0.71, miner => miner.outputItems("2x minecraft:copper_ingot"))
        .chance(0.70, miner => miner.outputItems("2x minecraft:lapis_lazuli"))
        .chance(0.70, miner => miner.outputItems("2x thermal:silver_ingot"))
        .chance(0.68, miner => miner.outputItems("2x thermal:nickel_ingot"))
        .chance(0.62, miner => miner.outputItems("2x minecraft:gold_ingot"))
        .chance(0.54, miner => miner.outputItems("2x thermal:tin_ingot"))
        .chance(0.95, miner => miner.outputItems("thermal:lead_ingot"))
        .chance(0.92, miner => miner.outputItems("evilcraft:dark_gem"))
        .chance(0.87, miner => miner.outputItems("mekanism:fluorite_gem"))
        .chance(0.85, miner => miner.outputItems("thermal:sulfur"))
        .chance(0.80, miner => miner.outputItems("thermal:niter"))
        .chance(0.77, miner => miner.outputItems("thermal:apatite"))
        .chance(0.52, miner => miner.outputItems("thermal:oil_sand"))
        .chance(0.40, miner => miner.outputItems("ae2:certus_quartz_crystal"))
        .chance(0.31, miner => miner.outputItems("thermal:cinnabar"))
        .chance(0.30, miner => miner.outputItems("ae2:silicon"))
        .chance(0.27, miner => miner.outputItems("forbidden_arcanus:arcane_crystal"))
        .chance(0.24, miner => miner.outputItems("minecraft:diamond"))
        .chance(0.22, miner => miner.outputItems("mekanism:ingot_uranium"))
        .chance(0.19, miner => miner.outputItems("minecraft:quartz"))
        .chance(0.13, miner => miner.outputItems("minecraft:emerald"))
        .chance(0.09, miner => miner.outputItems("forbidden_arcanus:rune"))
        .blocksInStructure(2, 2, "kubejs:overworld_quantum_modifier", "kubejs:auto_smelt_quantum_modifier")
        .priority(1)

        event.recipes.kubejs.quantum_miner()
        .id("kubejs:quantum_miner/overworld/normal/fortune")
        .duration(40)
        .perTick(miner => miner
            .inputFE(32768)
        )
        .chance(0.90, miner => miner.outputItems("9x minecraft:raw_iron"))
        .chance(0.96, miner => miner.outputItems("8x minecraft:redstone"))
        .chance(0.94, miner => miner.outputItems("4x mysticalagriculture:inferium_essence"))
        .chance(0.85, miner => miner.outputItems("4x minecraft:coal"))
        .chance(0.82, miner => miner.outputItems("4x mekanism:raw_osmium"))
        .chance(0.78, miner => miner.outputItems("4x minecraft:raw_copper"))
        .chance(0.77, miner => miner.outputItems("4x minecraft:lapis_lazuli"))
        .chance(0.77, miner => miner.outputItems("4x thermal:raw_silver"))
        .chance(0.75, miner => miner.outputItems("4x thermal:raw_nickel"))
        .chance(0.91, miner => miner.outputItems("3x minecraft:raw_gold"))
        .chance(0.79, miner => miner.outputItems("3x thermal:raw_tin"))
        .chance(0.70, miner => miner.outputItems("3x thermal:raw_lead"))
        .chance(0.67, miner => miner.outputItems("3x evilcraft:dark_gem"))
        .chance(0.96, miner => miner.outputItems("2x mekanism:fluorite_gem"))
        .chance(0.94, miner => miner.outputItems("2x thermal:sulfur"))
        .chance(0.88, miner => miner.outputItems("2x thermal:niter"))
        .chance(0.85, miner => miner.outputItems("2x thermal:apatite"))
        .chance(0.52, miner => miner.outputItems("thermal:oil_sand"))
        .chance(0.88, miner => miner.outputItems("ae2:certus_quartz_crystal"))
        .chance(0.68, miner => miner.outputItems("thermal:cinnabar"))
        .chance(0.66, miner => miner.outputItems("ae2:certus_quartz_dust"))
        .chance(0.60, miner => miner.outputItems("forbidden_arcanus:arcane_crystal"))
        .chance(0.53, miner => miner.outputItems("minecraft:diamond"))
        .chance(0.48, miner => miner.outputItems("mekanism:raw_uranium"))
        .chance(0.42, miner => miner.outputItems("minecraft:quartz"))
        .chance(0.29, miner => miner.outputItems("minecraft:emerald"))
        .chance(0.20, miner => miner.outputItems("forbidden_arcanus:rune"))
        .blocksInStructure(3, 3, "kubejs:overworld_quantum_modifier", "kubejs:blank_quantum_modifier", "kubejs:fortune_quantum_modifier")
        .priority(1)

    event.recipes.kubejs.quantum_miner()
        .id("kubejs:quantum_miner/overworld/auto_smelt/fortune")
        .duration(40)
        .perTick(miner => miner
            .inputFE(32768)
        )
        .chance(0.90, miner => miner.outputItems("9x minecraft:iron_ingot"))
        .chance(0.96, miner => miner.outputItems("8x minecraft:redstone"))
        .chance(0.94, miner => miner.outputItems("4x mysticalagriculture:inferium_essence"))
        .chance(0.85, miner => miner.outputItems("4x minecraft:coal"))
        .chance(0.82, miner => miner.outputItems("4x mekanism:ingot_osmium"))
        .chance(0.78, miner => miner.outputItems("4x minecraft:copper_ingot"))
        .chance(0.77, miner => miner.outputItems("4x minecraft:lapis_lazuli"))
        .chance(0.77, miner => miner.outputItems("4x thermal:silver_ingot"))
        .chance(0.75, miner => miner.outputItems("4x thermal:nickel_ingot"))
        .chance(0.91, miner => miner.outputItems("3x minecraft:gold_ingot"))
        .chance(0.79, miner => miner.outputItems("3x thermal:tin_ingot"))
        .chance(0.70, miner => miner.outputItems("3x thermal:lead_ingot"))
        .chance(0.67, miner => miner.outputItems("3x evilcraft:dark_gem"))
        .chance(0.96, miner => miner.outputItems("2x mekanism:fluorite_gem"))
        .chance(0.94, miner => miner.outputItems("2x thermal:sulfur"))
        .chance(0.88, miner => miner.outputItems("2x thermal:niter"))
        .chance(0.85, miner => miner.outputItems("2x thermal:apatite"))
        .chance(0.52, miner => miner.outputItems("thermal:oil_sand"))
        .chance(0.88, miner => miner.outputItems("ae2:certus_quartz_crystal"))
        .chance(0.68, miner => miner.outputItems("thermal:cinnabar"))
        .chance(0.66, miner => miner.outputItems("ae2:silicon"))
        .chance(0.60, miner => miner.outputItems("forbidden_arcanus:arcane_crystal"))
        .chance(0.53, miner => miner.outputItems("minecraft:diamond"))
        .chance(0.48, miner => miner.outputItems("mekanism:ingot_uranium"))
        .chance(0.42, miner => miner.outputItems("minecraft:quartz"))
        .chance(0.29, miner => miner.outputItems("minecraft:emerald"))
        .chance(0.20, miner => miner.outputItems("forbidden_arcanus:rune"))
        .blocksInStructure(3, 3, "kubejs:overworld_quantum_modifier", "kubejs:auto_smelt_quantum_modifier", "kubejs:fortune_quantum_modifier")
        .priority(0)
})