StartupEvents.registry('block', event => {

    //Multiblocks
    event.create('machinarium_casing').displayName('Machinarium Casing').soundType('stone')
        .hardness(5.0).resistance(4).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('blank_quantum_modifier').displayName('Blank Quantum Modifier').soundType('stone')
        .hardness(5).resistance(4).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').textureAll('kubejs:block/quantum_miner/blank_quantum_modifier')
    event.create('overworld_quantum_modifier').displayName('Overworld Quantum Modifier').soundType('stone')
        .hardness(5).resistance(4).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('nether_quantum_modifier').displayName('Nether Quantum Modifier').soundType('stone')
        .hardness(5).resistance(4).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('auto_smelt_quantum_modifier').displayName('Auto-Smelt Quantum Modifier').soundType('stone')
        .hardness(5).resistance(4).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('silk_touch_quantum_modifier').displayName('Silk Touch Quantum Modifier').soundType('stone')
        .hardness(5).resistance(4).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('fortune_quantum_modifier').displayName('Fortune Quantum Modifier').soundType('stone')
        .hardness(5).resistance(4).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')

    event.create('dielectric_paste_block').displayName('Dielectric Paste Block').soundType('wool')
        .hardness(3.0).resistance(1.0).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    //event.create('crystalline_pink_slime_block').displayName('Crystalline Pink Slime Block').soundType('metal')
    //  .hardness(5.0).resistance(2.5).requiresTool(true)
    //  .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('radiance_block').displayName('Radiance Block').soundType('wool')
        .hardness(3.0).resistance(1.5).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('compressed_crafting_table').displayName('Compressed Crafting Table').soundType('wood')
        .hardness(3.5).resistance(3.5).requiresTool(false)
    .tagBlock('minecraft:mineable/axe').tagBlock('minecraft:needs_iron_tool')
    event.create('double_compressed_crafting_table').displayName('Double Compressed Crafting Table').soundType('wood')
        .hardness(4.5).resistance(4.5).requiresTool(false)
        .tagBlock('minecraft:mineable/axe').tagBlock('minecraft:needs_iron_tool')
    event.create('quartz_ore').displayName('Quartz Ore').soundType('stone')
        .hardness(3).resistance(3).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_wooden_tool').tagBlock('forge:ores').tagBlock('forge:ores/quartz').item(t=>{t.tag('forge:ores').tag('forge:ores/quartz')})
    event.create('deepslate_quartz_ore').displayName('Deepslate Quartz Ore').soundType('deepslate')
        .hardness(4.5).resistance(3).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_wooden_tool').tagBlock('forge:ores').tagBlock('forge:ores/quartz').item(t=>{t.tag('forge:ores').tag('forge:ores/quartz')})
    event.create('certus_quartz_ore').displayName('Certus Quartz Ore').soundType('stone')
        .hardness(3).resistance(3).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_wooden_tool').tagBlock('forge:ores').tagBlock('forge:ores/certus_quartz').item(t=>{t.tag('forge:ores').tag('forge:ores/certus_quartz')})
    event.create('deepslate_certus_quartz_ore').displayName('Deepslate Certus Quartz Ore').soundType('deepslate')
        .hardness(4.5).resistance(3).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_wooden_tool').tagBlock('forge:ores').tagBlock('forge:ores/certus_quartz').item(t=>{t.tag('forge:ores').tag('forge:ores/certus_quartz')})   

    //Material Blocks
    event.create('neptune_block').displayName('Neptune Block').soundType('metal')
        .hardness(4.0).resistance(1.0).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('valkyrie_block').displayName('Valkyrie Block').soundType('metal')
        .hardness(5.0).resistance(2.0).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('phoenix_block').displayName('Phoenix Block').soundType('metal')
        .hardness(5.0).resistance(2.0).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('demon_block').displayName('Demon Block').soundType('metal')
        .hardness(5.0).resistance(2.0).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').item(fr=>{fr.fireResistant(true)})
    event.create('enchanted_block').displayName('Enchanted Block').soundType('metal')
        .hardness(4.0).resistance(2.0).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('evil_infused_block').displayName('Evil Infused Block').soundType('metal')
        .hardness(6.0).resistance(3.0).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('crystalline_alloy_block').displayName('Crystalline Alloy Block').soundType('metal')
        .hardness(5.0).resistance(2.5).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('dark_soul_infused_block').displayName('Dark Soul Infused Block').soundType('metal')
        .hardness(7.0).resistance(3.0).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').item(gl=>{gl.glow(true)})
    event.create('extradimensional_alloy_block').displayName('Extra-Dimensional Alloy Block').soundType('metal')
        .hardness(6.0).resistance(3.0).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')
    event.create('automaton_block').displayName('Automaton Block').soundType('metal')
        .hardness(8.0).resistance(4.0).requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool')


})